### ISSUE TITLE
Report folder issue

### ISSUE THREAD

**Issue by officiallysameer** [authorjapps/zerocode#19]
When there were no reports generated, it should have been validated and appropriate message shown to the user. e.g `target/zerocode-test-reports` was not present or generated or permission issue was encountered.

Is it possible to fix this aspect of the library?

But below error breaks the reports generation, as - 

`
Stacktrace was: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at java.util.Arrays$ArrayList.<init>(Arrays.java:3813)
	at java.util.Arrays.asList(Arrays.java:3800)
	at org.jsmart.zerocode.core.report.ZeroCodeReportGeneratorImpl.getAllEndPointFilesFrom(ZeroCodeReportGeneratorImpl.java:201)
	at org.jsmart.zerocode.core.report.ZeroCodeReportGeneratorImpl.readZeroCodeReportsByPath(ZeroCodeReportGeneratorImpl.java:174)
	at org.jsmart.zerocode.core.report.ZeroCodeReportGeneratorImplTest.testReportFolderNotPresentInTarget_validation
`

**Comment by dinesh76in** [comment]
@authorjapps , Raised the PR for the folder validation. Please review n approve.

**Comment by authorjapps** [comment]
@dinesh76in , Thanks for fixing #20 . Fix available with `version 1.1.21` onwards.
