### ISSUE TITLE
Kafka-produce and consume JSON message, Assert fails for 'consume' operation

### ISSUE THREAD

**Issue by rahul-mali-mpf** [authorjapps/zerocode#237]
I am trying to produce as well consume the Kafka message but application is failing for 'consume' operation. Please see below details:
- Git cloned "https://github.com/authorjapps/hello-kafka-stream-testing".
- Trying to execute the test **'KafkaProduceJsonTest'** 
- For above execution updated the "test_kafka_produce_json_record.json" file with my topic name.
- Updated the "kafka_test_server_int_key.properties" file with my Kafka host details. Also updated remaining files with my Kafka host details
With above details when executing the test "KafkaProduceJsonTest" its produces the message successfully however failing with assertion error as below:
----------------------------------- Error-----------------------------------------------------------------
value.deserializer = class org.apache.kafka.common.serialization.StringDeserializer

2019-05-03 17:52:42,914 [main] INFO  org.apache.kafka.common.utils.AppInfoParser - Kafka version : 2.1.0
2019-05-03 17:52:42,914 [main] INFO  org.apache.kafka.common.utils.AppInfoParser - Kafka commitId : eec43959745f444f
2019-05-03 17:52:42,915 [main] INFO  org.jsmart.zerocode.core.kafka.receive.KafkaReceiver - polling records  - noOfTimeOuts reached : 0
2019-05-03 17:52:43,916 [main] INFO  org.jsmart.zerocode.core.kafka.receive.KafkaReceiver - polling records  - noOfTimeOuts reached : 1
2019-05-03 17:52:44,155 [main] INFO  org.apache.kafka.clients.Metadata - Cluster ID: 5UsXaZN0Smi4cuXoEL1zaw
2019-05-03 17:52:44,348 [main] INFO  org.apache.kafka.clients.consumer.internals.AbstractCoordinator - [Consumer clientId=consumer-1, groupId=consumerGroup14] Discovered group coordinator xx-kafka-host-xx:9092 (id: 2147483646 rack: null)
2019-05-03 17:52:44,355 [main] INFO  org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-1, groupId=consumerGroup14] Revoking previously assigned partitions []
2019-05-03 17:52:44,356 [main] INFO  org.apache.kafka.clients.consumer.internals.AbstractCoordinator - [Consumer clientId=consumer-1, groupId=consumerGroup14] (Re-)joining group
2019-05-03 17:52:44,918 [main] INFO  org.jsmart.zerocode.core.kafka.receive.KafkaReceiver - polling records  - noOfTimeOuts reached : 2
2019-05-03 17:52:45,910 [main] INFO  org.apache.kafka.clients.consumer.internals.AbstractCoordinator - [Consumer clientId=consumer-1, groupId=consumerGroup14] Successfully joined group with generation 3
2019-05-03 17:52:45,912 [main] INFO  org.apache.kafka.clients.consumer.internals.ConsumerCoordinator - [Consumer clientId=consumer-1, groupId=consumerGroup14] Setting newly assigned partitions [mytopic-2, mytopic-0, mytopic-1]
2019-05-03 17:52:45,919 [main] INFO  org.jsmart.zerocode.core.kafka.receive.KafkaReceiver - polling records  - noOfTimeOuts reached : 3
2019-05-03 17:52:46,921 [main] INFO  org.apache.kafka.clients.consumer.internals.AbstractCoordinator - [Consumer clientId=consumer-1, groupId=consumerGroup14] Sending LeaveGroup request to coordinator xx-kafka-host-xx:9092 (id: 2147483646 rack: null)
2019-05-03 17:52:47,356 [main] WARN  org.jsmart.zerocode.core.engine.assertion.JsonAsserter - Path: $.records[0].key was not found in the response. Hence this value was treated as null.
2019-05-03 17:52:47,358 [main] WARN  org.jsmart.zerocode.core.engine.assertion.JsonAsserter - Path: $.records[0].value.name was not found in the response. Hence this value was treated as null.
2019-05-03 17:52:47,374 [main] ERROR org.jsmart.zerocode.core.runner.StepNotificationHandler - Failed assertion during Scenario:Produce a JSON message to a kafka topic, --> Step:consume_step, Details: Assertion path '$.records[0].key' with actual value 'null' did not match the expected value '101'
Assertion path '$.records[0].value.name' with actual value 'null' did not match the expected value 'Jey'

2019-05-03 17:52:47,379 [main] ERROR org.jsmart.zerocode.core.runner.StepNotificationHandler - Assertion failed for :- 

[Produce a JSON message to a kafka topic] 
	|
	|
	+---Step --> [consume_step] 

Failures:
--------- 
Assertion path '$.records[0].key' with actual value 'null' did not match the expected value '101'
--------------------------------------------------------------------------------------------------------
Assertion path '$.records[0].value.name' with actual value 'null' did not match the expected value 'Jey'
(See below 'Actual Vs Expected' to learn why this step failed) 

java.lang.RuntimeException: Assertion failed for :- 

[Produce a JSON message to a kafka topic] 
	|
	|
	+---Step --> [consume_step] 

Failures:
--------- 
Assertion path '$.records[0].key' with actual value 'null' did not match the expected value '101'
--------------------------------------------------------------------------------------------------------
Assertion path '$.records[0].value.name' with actual value 'null' did not match the expected value 'Jey'

	at org.jsmart.zerocode.core.runner.StepNotificationHandler.handleAssertionFailed(StepNotificationHandler.java:37)
	at org.jsmart.zerocode.core.runner.StepNotificationHandler.handleAssertion(StepNotificationHandler.java:71)
	at org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl.runScenario(ZeroCodeMultiStepsScenarioRunnerImpl.java:274)
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.runLeafJsonTest(ZeroCodeUnitRunner.java:198)
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.runChild(ZeroCodeUnitRunner.java:118)
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.runChild(ZeroCodeUnitRunner.java:45)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.run(ZeroCodeUnitRunner.java:101)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

2019-05-03 17:52:47,414 [main] INFO  org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl - 
--------- TEST-STEP-CORRELATION-ID: ef57c1a2-e920-450c-bbcd-7160a7eff6ca ---------
*requestTimeStamp:2019-05-03T17:52:42.654
step:consume_step
url:kafka-topic:mytopic
method:consume
request:
{
  "consumerLocalConfigs" : {
    "recordType" : "JSON",
    "commitSync" : true,
    "maxNoOfRetryPollsOrTimeouts" : 3,
    "showRecordsConsumed" : true,
    "pollingTime" : 1000
  }
} 
--------- TEST-STEP-CORRELATION-ID: ef57c1a2-e920-450c-bbcd-7160a7eff6ca ---------
Response:
{
  "records" : [ ],
  "size" : 0
}
*responseTimeStamp:2019-05-03T17:52:47.342 
*Response delay:4688.0 milli-secs 
---------> Assertion: <----------
Assertion path '$.records[0].key' with actual value 'null' did not match the expected value '101'
Assertion path '$.records[0].value.name' with actual value 'null' did not match the expected value 'Jey'
 
-done-

2019-05-03 17:52:47,628 [main] INFO  org.jsmart.zerocode.core.engine.listener.ZeroCodeTestReportListener - ### ZeroCode: Test run completed for this runner. Generating test reports and charts. More help and examples are available at the README in GitHub
2019-05-03 17:52:47,983 [main] INFO  org.jsmart.zerocode.core.domain.builders.ExtentReportsFactory - Where were the tests fired? Ans: OS:Linux, Architecture:amd64, Java:1.8.0_181
-------------------------------------------------------------------------------------------------------------------------------
Please ignore topic name and host name as I have changed them for security reasons.
Tried below solutions but no luck:
1. Commented out the 'produce' operation and execute test for 'consume' operation only. But it is not working.
2. Tried with running producer and consumer in one go but still its failing.

Please suggest a solution for this.
Also please let me know if more details are required.

**Comment by authorjapps** [comment]
Hello @rahul-mali-mpf, We will have a look soon n get back here.
Looks like you have shared the important bits(great stuff 👍), we might ask for more details if needed.

**Comment by rahul-mali-mpf** [comment]
It was kafka configuration issue. Resolved now.

**Comment by dineshr226** [comment]
> It was kafka configuration issue. Resolved now.

Hi Rahul, could tell me what was configuration issue here and how to resolve it... I am also facing same.

**Comment by rahul-mali-mpf** [comment]
Kafka was running in Docker container. And Dev team writes the Docker file for kafka docker Image.
They updated the Docker file and created new Kafka Docker image. The updated Kafka docker image is able to receive and consume the messages. Not remember exactly as its too old issue but i believe they updated the Kafka configuration to accept the messages globally.
For now this is the only info I have. Sorry if it does not help you.

**Comment by kt0984** [comment]
Hi @rahul-mali-mpf ,

I am having the exact same problem. I have a topic with several thousands of messages in it. I just want to produce a message, consume that exact message and validate the data returned. Producing works fine. On consumption, I am getting the same error you were getting. 
My Kafka is not running in Docker, it is on Amazon's managed portal MSK. 

Any help in this regard will be much appreciated. If you can attach your .properties file then it may help unblock me. 

Regards,
Kushagra

**Comment by authorjapps** [comment]
It all works fine now as expected @kt0984 . This has been sorted over the Slack n web-meeting Y'day evening. Thanks for your patience Y'day over the discussion 🤗 

Happy testing once again 🐼

**Comment by ddingel** [comment]
Hi @kt0984 @authorjapps,

We are facing the same issue on AWS MSK and are not able to consume messages from zerocode, but other consumers work fine. Setup is with SSL if that matters. Local with kafka in a docker container it just works. Can you share your solution to this.

Thanks,
Dominik

**Comment by ddingel** [comment]
Answering myself: so we managed to fix this by increasing the pollingTime to 2000 for that consume step.

I am not sure why this solves the problem, my wild guess would be something like the consumer looking up the broker for that partition, registering and such exceeds the 500ms so that we end before we actually receive anything.
