### ISSUE TITLE
Test mechanism exception

### ISSUE THREAD

**Issue by automatedbegginer** [authorjapps/zerocode#352]
Hi,

I have done some new tests and start getting following exception in one module:

java.lang.RuntimeException: Exception while deserializing to ZeroCodeReport. Details: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (File); line: 1, column: 0]

	at org.jsmart.zerocode.core.report.ZeroCodeReportGeneratorImpl.lambda$readZeroCodeReportsByPath$36(ZeroCodeReportGeneratorImpl.java:327)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.jsmart.zerocode.core.report.ZeroCodeReportGeneratorImpl.readZeroCodeReportsByPath(ZeroCodeReportGeneratorImpl.java:331)
	at org.jsmart.zerocode.core.report.ZeroCodeReportGeneratorImpl.generateCsvReport(ZeroCodeReportGeneratorImpl.java:185)
	at org.jsmart.zerocode.core.engine.listener.ZeroCodeTestReportListener.generateChartsAndReports(ZeroCodeTestReportListener.java:48)
	at org.jsmart.zerocode.core.engine.listener.ZeroCodeTestReportListener.testRunFinished(ZeroCodeTestReportListener.java:43)
	at org.junit.runner.notification.SynchronizedRunListener.testRunFinished(SynchronizedRunListener.java:42)
	at org.junit.runner.notification.RunNotifier$2.notifyListener(RunNotifier.java:103)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	at org.junit.runner.notification.RunNotifier.fireTestRunFinished(RunNotifier.java:100)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

Tests are passing but Test Mechanism fails every time.

Best

ab

**Comment by authorjapps** [comment]
@automatedbegginer , Which IDE do you use?

**Comment by automatedbegginer** [comment]
Intellij

**Comment by nirmalchandra** [comment]
Can you do a `mvn clean install -DskipTests` first, just to make sure you have a clean build ?
Then run the test.

Also, can you stick the `Scenario` JSON file to this ticket to have a look?

**Comment by automatedbegginer** [comment]
Clean build helped. I am still not used to building and compiling application :) , since i used python so far. Thank you very much for help.
