### ISSUE TITLE
Intermittent MismatchedInputException when load testing

### ISSUE THREAD

**Issue by donfiguerres** [authorjapps/zerocode#400]
I'm getting an intermittent MismatchedInputException when running with ZeroCodeLoadRunner. 

    2020-06-08 17:59:22,127 [pool-2-thread-3] INFO org.jsmart.zerocode.core.engine.listener.ZeroCodeTestReportListener - ### ZeroCode: Test run completed for this runner. Generating test reports and charts. More help and examples are available at the README in GitHub
    com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
     at [Source: (File); line: 1, column: 0]
            at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
            at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4145)
            at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
            at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2902)
            at org.jsmart.zerocode.core.report.ZeroCodeReportGeneratorImpl.lambda$readZeroCodeReportsByPath$13(ZeroCodeReportGeneratorImpl.java:308)
            at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
            at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
            at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
            at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
            at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
            at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
            at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
            at org.jsmart.zerocode.core.report.ZeroCodeReportGeneratorImpl.readZeroCodeReportsByPath(ZeroCodeReportGeneratorImpl.java:317)
            at org.jsmart.zerocode.core.report.ZeroCodeReportGeneratorImpl.generateCsvReport(ZeroCodeReportGeneratorImpl.java:171)
            at org.jsmart.zerocode.core.engine.listener.ZeroCodeTestReportListener.generateChartsAndReports(ZeroCodeTestReportListener.java:48)
            at org.jsmart.zerocode.core.engine.listener.ZeroCodeTestReportListener.testRunFinished(ZeroCodeTestReportListener.java:43)
            at org.junit.runner.notification.SynchronizedRunListener.testRunFinished(SynchronizedRunListener.java:42)
            at org.junit.runner.notification.RunNotifier$2.notifyListener(RunNotifier.java:103)
            at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
            at org.junit.runner.notification.RunNotifier.fireTestRunFinished(RunNotifier.java:100)
            at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
            at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
            at org.jsmart.zerocode.core.runner.parallel.LoadProcessor.lambda$createRunnable$23(LoadProcessor.java:59)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
            at java.lang.Thread.run(Thread.java:748)
    2020-06-08 17:59:22,149 [pool-2-thread-3] INFO org.jsmart.zerocode.core.runner.parallel.LoadProcessor - pool-2-thread-3 Parallel Junit test- *  End. Time = 2020-06-08T17:59:22.149

My properties file has these values. I noticed I start getting this error when I add too many threads.

    number.of.threads=40
    ramp.up.period.in.seconds=5
    loop.count=2

**Comment by donfiguerres** [comment]
I did an quick debugging and I'm wondering if the call to generateChartsAndReports(); can be delayed until the LoadTest is complete. I'm not really sure about this but it seems the problem occurs when too many threads are reading the json files in target/zerocode-test-reports (at least that's what I observe in my environment).

**Comment by authorjapps** [comment]
Hi,
The below seems to be a moderate load, but that depends on which system it is running.
```
number.of.threads=40
ramp.up.period.in.seconds=5
loop.count=2
```

Trying to figure out...

What kind of machine did you run this on?
CPU- how many cores? 
RAM- how many GB
payload size? approximate KB ?

Did you investigate the CSV file it generates in the target folder? 
That gives very accurate results from which you can derive the throughput easily..

**Comment by donfiguerres** [comment]
Sorry, it took me a long time to respond. I had to prioritize other tasks.
It discovered that this is caused by VSCode.
It's probably trying to access the newly generated CSV files while zero-code is running. I was running the tests via the Java extension of VSCode and when I decided to close VSCode and run the tests via command line, the issue disappeared. I'm closing this issue now. Thanks!

**Comment by donfiguerres** [comment]
Another update... I got a few errors again today even after running with VSCode closed. I won't reopen this though since I'm pretty sure now that the problem has something to do with my environment.
