### ISSUE TITLE
reading the value from property file and placing in uri request and getting error

### ISSUE THREAD

**Issue by ramachandrakambham** [authorjapps/zerocode#460]
```json
{
  "name": "find_backendautomation_org",
  "url": "org.jsmart.zerocode.converter.MimeTypeConverter",
  "operation": "stringToJson",
  "request": "${$.Fetch_Organization.response.body.successResult.organziations[?(@.name=='${web.application.yell.account.id}')].id}",
  "assertions": []
}
```

error :
```java
[0;39mjava.lang.RuntimeException: 
JSON:"${$.Fetch_Organization.response.body.successResult.organziations[(@.name=='${web.application.yell.account.id}')].id}"
Possibly comments in the JSON found or bad JSON path found: $.Fetch_Organization.response.body.successResult.organziations[(@.name=='${web.application.yell.account.id,
Details: com.jayway.jsonpath.InvalidPathException: Could not parse token starting at position 62. Expected ?, ', 0-9, * 
	at org.jsmart.zerocode.core.engine.preprocessor.ZeroCodeAssertionsProcessorImpl.lambda$resolveJsonPaths$46(ZeroCodeAssertionsProcessorImpl.java:154)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.jsmart.zerocode.core.engine.preprocessor.ZeroCodeAssertionsProcessorImpl.resolveJsonPaths(ZeroCodeAssertionsProcessorImpl.java:120)
	at org.jsmart.zerocode.core.engine.preprocessor.ZeroCodeAssertionsProcessorImpl.resolveStringJson(ZeroCodeAssertionsProcessorImpl.java:90)
```

**Comment by RDBreed** [comment]
Your path is incorrect. And that is exactly the message you are getting. 
Could you describe more what you want to achieve here?

Btw, in your request it is `${$.Fetch_Organization.response.body.successResult.organziations[?(@.name=='${web.application.yell.account.id}')].id}` and below in the response exception `${$.Fetch_Organization.response.body.successResult.organziations[(@.name=='${web.application.yell.account.id}')].id}` (without the question mark)...

**Comment by sparrowV** [comment]
Thanks @RDBreed . @ramachandrakambham  Do you have any questions regarding with this ?
