### ISSUE TITLE
Zerocode is not able to read the response from server 

### ISSUE THREAD

**Issue by pavithra0530** [authorjapps/zerocode#484]
I can see the api call is coming to the server and also the response that is sent from my server in my server logs but zero code shows response unavailable. The same api call is working fine through post man. Please help.

**test case:**

```java
package com.ekart.citylogistics.payment.test;

import com.flipkart.zeta.testconfig.E2eJunitRunner;
import org.jsmart.zerocode.core.domain.JsonTestCase;
import org.jsmart.zerocode.core.domain.TargetEnv;
import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.MethodSorters;

@TargetEnv("application-local.properties")
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
@RunWith(E2eJunitRunner.class)
public class CreateShipementTest {


    @Test
    @JsonTestCase("testSteps/createShipmentExpectation.json")
    public void createShipmentExpectation() {
    }

}

```

**Run console:** 

```
2021-02-26 11:07:58,571 [main] INFO org.jsmart.zerocode.core.engine.preprocessor.ZeroCodeExternalFileProcessorImpl - Found external JSON file place holder = ${JSON.FILE:jsonRequests/shipmentCreateSingle.json}. Replacing with content
2021-02-26 11:07:58,676 [main] INFO org.jsmart.zerocode.core.httpclient.ssl.SslTrustHttpClient - ###Used SSL Enabled Http Client for http/https/TLS connections
2021-02-26 11:07:59,013 [main] INFO org.jsmart.zerocode.core.httpclient.utils.HeaderUtils - Overridden the header key:X-REQUEST-ID, with value:HL123
**2021-02-26 11:07:59,709 [main] ERROR org.jsmart.zerocode.core.engine.executor.ApiServiceExecutorImpl - Ooooooooooops! Something unexpected happened while connecting to the url:http://127.0.0.1:46000/v1/shipments/bulk** 
1) Check if the service is running at the host -or-
2) Check the corporate proxy has been configured correctly -or
3) Choose another mocking(if in use) port not to conflict with the port:0 -or-
4) Restart the service. -or- See the full error details below-
java.lang.RuntimeException: java.lang.AbstractMethodError: javax.ws.rs.core.Response.hasEntity()Z
{}
java.lang.AbstractMethodError: javax.ws.rs.core.Response.hasEntity()Z
	at javax.ws.rs.core.Response.fromResponse(Response.java:570) ~[javax.ws.rs-api-2.0.1.jar:2.0.1]
	at org.jsmart.zerocode.core.engine.executor.ApiServiceExecutorImpl.executeHttpApi(ApiServiceExecutorImpl.java:42)
	at org.jsmart.zerocode.core.httpclient.BasicHttpClient.handleResponse(BasicHttpClient.java:163) ~[zerocode-tdd-1.3.24.jar:na]
	at org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl.executeApi(ZeroCodeMultiStepsScenarioRunnerImpl.java:411)
	at org.jsmart.zerocode.core.httpclient.BasicHttpClient.execute(BasicHttpClient.java:147) ~[zerocode-tdd-1.3.24.jar:na]
	at org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl.executeRetry(ZeroCodeMultiStepsScenarioRunnerImpl.java:227)
	at org.jsmart.zerocode.core.engine.executor.httpapi.HttpApiExecutorImpl.execute(HttpApiExecutorImpl.java:62) ~[zerocode-tdd-1.3.24.jar:na]
	at org.jsmart.zerocode.core.engine.executor.ApiServiceExecutorImpl.executeHttpApi(ApiServiceExecutorImpl.java:33) ~[zerocode-tdd-1.3.24.jar:na]
	at org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl.executeRetryWithSteps(ZeroCodeMultiStepsScenarioRunnerImpl.java:178)
	at org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl.executeApi(ZeroCodeMultiStepsScenarioRunnerImpl.java:411) [zerocode-tdd-1.3.24.jar:na]
	at org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl.executeRetry(ZeroCodeMultiStepsScenarioRunnerImpl.java:227) [zerocode-tdd-1.3.24.jar:na]
	at org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl.executeSteps(ZeroCodeMultiStepsScenarioRunnerImpl.java:162)
	at org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl.executeRetryWithSteps(ZeroCodeMultiStepsScenarioRunnerImpl.java:178) [zerocode-tdd-1.3.24.jar:na]
	at org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl.runScenario(ZeroCodeMultiStepsScenarioRunnerImpl.java:125)
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.runLeafJsonTest(ZeroCodeUnitRunner.java:223)
	at org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl.executeSteps(ZeroCodeMultiStepsScenarioRunnerImpl.java:162) [zerocode-tdd-1.3.24.jar:na]
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.runChild(ZeroCodeUnitRunner.java:127)
	at org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl.runScenario(ZeroCodeMultiStepsScenarioRunnerImpl.java:125) [zerocode-tdd-1.3.24.jar:na]
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.runLeafJsonTest(ZeroCodeUnitRunner.java:223) [zerocode-tdd-1.3.24.jar:na]
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.runChild(ZeroCodeUnitRunner.java:51)
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.runChild(ZeroCodeUnitRunner.java:127) [zerocode-tdd-1.3.24.jar:na]
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.runChild(ZeroCodeUnitRunner.java:51) [zerocode-tdd-1.3.24.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.run(ZeroCodeUnitRunner.java:107)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.run(ZeroCodeUnitRunner.java:107) [zerocode-tdd-1.3.24.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68) [junit-rt.jar:na]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33) [junit-rt.jar:na]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230) [junit-rt.jar:na]
Caused by: java.lang.AbstractMethodError: javax.ws.rs.core.Response.hasEntity()Z
	at javax.ws.rs.core.Response.fromResponse(Response.java:570)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58) [junit-rt.jar:na]
	at org.jsmart.zerocode.core.httpclient.BasicHttpClient.handleResponse(BasicHttpClient.java:163)
	at org.jsmart.zerocode.core.httpclient.BasicHttpClient.execute(BasicHttpClient.java:147)
	at org.jsmart.zerocode.core.engine.executor.httpapi.HttpApiExecutorImpl.execute(HttpApiExecutorImpl.java:62)
2021-02-26 11:07:59,711 	at org.jsmart.zerocode.core.engine.executor.ApiServiceExecutorImpl.executeHttpApi(ApiServiceExecutorImpl.java:33)
	... 20 more
[main] ERROR org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl - ###Exception while executing a step in the zerocode dsl.
**2021-02-26 11:07:59,713 [main] ERROR org.jsmart.zerocode.core.runner.StepNotificationHandler - Exception occurred while executing Scenario:[Create Shipment Expectation in Payments], --> Step:[Create Shipment Expectation], Details: java.lang.RuntimeException: ZeroCode Step execution failed. Details:java.lang.RuntimeException: java.lang.AbstractMethodError: javax.ws.rs.core.Response.hasEntity()Z**
2021-02-26 11:07:59,720 [main] WARN org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl - 
--------- TEST-STEP-CORRELATION-ID: cc018c0f-fffb-4b52-96e3-095abc0794a6 ---------
*requestTimeStamp:2021-02-26T11:07:58.616
step:Create Shipment Expectation
id:null
url:http://127.0.0.1:46000/v1/shipments/bulk
method:POST
request:
{
  "headers" : {
    "X-REQUEST-ID" : "HL123"
  },
  "body" : {
    "shipmentRequests" : [ {
      "shipmentId" : "PAYSHIP800008",
      "hubId" : "89418",
      "lineOfBusiness" : "HYPERLOCAL",
      "runsheetId" : 19000001,
      "expectations" : [ {
        "amount" : 55555.0,
        "externalId" : "SHIPITEM800008"
      }, {
        "amount" : 66666.0,
        "externalId" : "SHIPITEM800009"
      } ]
    }, {
      "shipmentId" : "PAYSHIPM800010",
      "hubId" : "89418",
      "lineOfBusiness" : "HYPERLOCAL",
      "runsheetId" : 19000002,
      "expectations" : [ {
        "amount" : 77777.0,
        "externalId" : "SHIPITEM800010"
      } ]
    } ]
  }
} 
**--------- TEST-STEP-CORRELATION-ID: cc018c0f-fffb-4b52-96e3-095abc0794a6 ---------
Response:
-response unavailable-
*responseTimeStamp:2021-02-26T11:07:59.711 
*Response delay:1095.0 milli-secs 
---------> Expected Response: <----------
{Oops! Not decided. Possibly due to non JSON content was encountered. See log for details} 
 
-done-**


java.lang.RuntimeException: ZeroCode Step execution failed. Details:java.lang.RuntimeException: java.lang.AbstractMethodError: javax.ws.rs.core.Response.hasEntity()Z

	at org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl.executeRetry(ZeroCodeMultiStepsScenarioRunnerImpl.java:344)
	at org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl.executeRetryWithSteps(ZeroCodeMultiStepsScenarioRunnerImpl.java:178)
	at org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl.executeSteps(ZeroCodeMultiStepsScenarioRunnerImpl.java:162)
	at org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl.runScenario(ZeroCodeMultiStepsScenarioRunnerImpl.java:125)
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.runLeafJsonTest(ZeroCodeUnitRunner.java:223)
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.runChild(ZeroCodeUnitRunner.java:127)
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.runChild(ZeroCodeUnitRunner.java:51)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.run(ZeroCodeUnitRunner.java:107)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

2021-02-26 11:07:59,851 [main] INFO org.jsmart.zerocode.core.engine.listener.ZeroCodeTestReportListener - #ZeroCode: Test run completed for this runner. Generating test reports and charts. 
* For more examples and help on automated Kafka data stream testing and Load testing visit https://zerocode.io
2021-02-26 11:07:59,930 [main] INFO org.jsmart.zerocode.core.domain.builders.ExtentReportsFactory - Where were the tests fired? Ans: OS:Mac OS X, Architecture:x86_64, Java:1.8.0_231, Vendor:Oracle Corporation

Process finished with exit code 255
```

**Comment by sparrowV** [comment]
Greetings, Can you share createShipmentExpectation.json scenario file and  application-local.properties file?

**Comment by pavithra0530** [comment]
Hi @sparrowV , Please find the details below:

**CreateShipementExpectation.json:**
{
  "scenarioName": "Create Shipment Expectation in Payments",
  "steps":[
    {
      "name": "Create Shipment Expectation",
      "url": "http://127.0.0.1:46000/v1/shipments/bulk",
      "operation": "POST",
      "request": {
        "headers":{
          "X-REQUEST-ID" : "HL123"
        },
        "body": "${JSON.FILE:jsonRequests/shipmentCreateSingle.json}"

      },
      "verify": {.  _**--->>> I have tried using assert also**_
        "status": 201,
        "body": {}
  }
  }
  ]
}

**application-local.properties:**
shipmentCreation.url=http://127.0.0.1:46000
restful.application.endpoint.host=http://127.0.0.1
restful.application.endpoint.port=46000
restful.application.endpoint.context=

**Server logs:**
2021-02-28 19:18:51.186 9c14c6f8-e4f6-48b8-a1b0-af21acba72e6 DEBUG 2745 --- [io-46000-exec-3] o.s.w.f.CommonsRequestLoggingFilter      : Before request [uri=/v1/shipments/bulk] 
Hibernate: 
    select
        shipment0_.id as id1_19_,
        shipment0_.created_at as created_2_19_,
        shipment0_.updated_at as updated_3_19_,
        shipment0_.version as version4_19_,
        shipment0_.hub_id as hub_id5_19_,
        shipment0_.line_of_business as line_of_6_19_,
        shipment0_.runsheet_id as runsheet7_19_,
        shipment0_.shipment_id as shipment8_19_,
        shipment0_.state as state9_19_ 
    from
        shipments shipment0_ 
    where
        shipment0_.shipment_id in (
            ? , ?
        )
2021-02-28 19:18:51.231 9c14c6f8-e4f6-48b8-a1b0-af21acba72e6  INFO 2745 --- [io-46000-exec-3] c.e.c.payment.services.ShipmentService   : Duplicate shipment creation request for id PAYSHIP800008, runsheet 19000001, and LOB HYPERLOCAL 
2021-02-28 19:18:51.232 9c14c6f8-e4f6-48b8-a1b0-af21acba72e6  INFO 2745 --- [io-46000-exec-3] c.e.c.payment.services.ShipmentService   : Duplicate shipment creation request for id PAYSHIPM800010, runsheet 19000002, and LOB HYPERLOCAL 
**2021-02-28 19:18:51.240 9c14c6f8-e4f6-48b8-a1b0-af21acba72e6 DEBUG 2745 --- [io-46000-exec-3] o.s.w.f.CommonsRequestLoggingFilter      : REQUEST_DATA : uri=/v1/shipments/bulk;payload={"shipmentRequests":[{"shipmentId":"PAYSHIP800008","hubId":"89418","lineOfBusiness":"HYPERLOCAL","runsheetId":19000001,"expectations":[{"amount":55555.0,"externalId":"SHIPITEM800008"},{"amount":66666.0,"externalId":"SHIPITEM800009"}]},{"shipmentId":"PAYSHIPM800010","hubId":"89418","lineOfBusiness":"HYPERLOCAL","runsheetId":19000002,"expectations":[{"amount":77777.0,"externalId":"SHIPITEM800010"}]}]}]**

**Comment by pavithra0530** [comment]
hey @sparrowV , Thanks for this one. But i have already tried that way and still I was getting same error.

**Comment by sparrowV** [comment]
@pavithra0530  Does the server return the data? Can you debug it and see if server return something?

**Comment by pavithra0530** [comment]
this issue is fixed ..  had problems with dependencies. below one fixed the issue:
dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    testCompile("com.flipkart:zeta:0.0.3-SNAPSHOT")
    testCompile 'org.junit.platform:junit-platform-commons:1.5.2'
    implementation group: 'org.jsmart', name: 'zerocode-tdd', version: '1.3.24'
}

**Comment by sparrowV** [comment]
Great @pavithra0530 , thanks for sharing the solution.
