### ISSUE TITLE
Method Invoke Error

### ISSUE THREAD

**Issue by AlindGit** [authorjapps/zerocode#541]
Getting exception while  going for DB validation via zero code as below:-
2022-10-18 22:17:36,436 [main] ERROR org.jsmart.zerocode.core.engine.executor.ApiServiceExecutorImpl - Java method execution exception - java.lang.RuntimeException: java.lang.RuntimeException: Java exec(): Invocation failed for method executeSimpleSql in class Com.wibmo.utility.PostGresSqlExecutor
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: Java exec(): Invocation failed for method executeSimpleSql in class Com.wibmo.utility.PostGresSqlExecutor
	at org.jsmart.zerocode.core.engine.executor.ApiServiceExecutorImpl.executeJavaOperation(ApiServiceExecutorImpl.java:52)
	at org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl.executeApi(ZeroCodeMultiStepsScenarioRunnerImpl.java:425)
	at org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl.executeRetry(ZeroCodeMultiStepsScenarioRunnerImpl.java:227)
	at org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl.executeRetryWithSteps(ZeroCodeMultiStepsScenarioRunnerImpl.java:178)
	at org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl.executeSteps(ZeroCodeMultiStepsScenarioRunnerImpl.java:162)
	at org.jsmart.zerocode.core.runner.ZeroCodeMultiStepsScenarioRunnerImpl.runScenario(ZeroCodeMultiStepsScenarioRunnerImpl.java:125)
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.runLeafJsonTest(ZeroCodeUnitRunner.java:223)
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.runChild(ZeroCodeUnitRunner.java:127)
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.runChild(ZeroCodeUnitRunner.java:51)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner.run(ZeroCodeUnitRunner.java:107)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Java exec(): Invocation failed for method executeSimpleSql in class Com.wibmo.utility.PostGresSqlExecutor
	at org.jsmart.zerocode.core.engine.executor.javaapi.JavaMethodExecutorImpl.execute(JavaMethodExecutorImpl.java:56)
	at org.jsmart.zerocode.core.engine.executor.ApiServiceExecutorImpl.executeJavaOperation(ApiServiceExecutorImpl.java:49)
	... 21 more
Caused by: java.lang.RuntimeException: Java exec(): Invocation failed for method executeSimpleSql in class Com.wibmo.utility.PostGresSqlExecutor
	at org.jsmart.zerocode.core.engine.executor.javaapi.JavaMethodExecutorImpl.executeWithParams(JavaMethodExecutorImpl.java:83)
	at org.jsmart.zerocode.core.engine.executor.javaapi.JavaMethodExecutorImpl.execute(JavaMethodExecutorImpl.java:48)
	... 22 more

I Reffered the blog here 👎 https://github.com/authorjapps/zerocode/issues/487

My DB credentials are correct:-
## ---------------------------
db_host_url=jdbc:mysql://XX.XX.XX.XXX:3306/myDB
db_username=admin
db_password=pass_word

code snippet:-
package Com.wibmo.utility;

import java.lang.reflect.InvocationTargetException;
//import mysql*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.inject.Inject;
import javax.inject.Named;
import javax.sql.DataSource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.mysql.*;
import com.mysql.jdbc.Driver;

public class PostGresSqlExecutor{
	
  private static final Logger LOGGER = LoggerFactory.getLogger(PostGresSqlExecutor.class);
  Map<String, List<Map<String, Object>>> dbRecordsMap = new HashMap<>();
  public static final String RESULTS_KEY = "rows";
  Connection conn = null;
//
	@Inject
	@Named("db_host_url")
     private String dbHostUrl;
	
	@Inject
    @Named("db_username")
    private String dbUserName;
	
	 @Inject
	@Named("db_password")
	private String dbPassword;
	 
	 
	 public Map<String, List<Map<String, Object>>> executeSimpleSql(String simpleSql) throws IllegalAccessException, InvocationTargetException, InstantiationException {

	      LOGGER.info("DB - Executing SQL query: {}", simpleSql);
	      System.out.println("going to execute query"+simpleSql);
	      System.out.println("hello test 1");
	//
	      List<Map<String, Object>> recordsList = fetchDbRecords(simpleSql);
	//
//	      // -------------------------------------------------------
//	      // Put all the fetched rows into nice JSON key and return.
//	      // -- This make it better to assert SIZE etc in the steps.
//	      // -- You can choose any key.
//	      // -------------------------------------------------------
	      dbRecordsMap.put(RESULTS_KEY, recordsList);
	//
	      return dbRecordsMap;
	//  }
		
	}

	 
	 
	 
	 
	 
	 private Connection getjdbcconnection()throws IllegalAccessException, InvocationTargetException, InstantiationException{
		 
		 try {
		 Class.forName("com.mysql.jdbc.Driver");  
		 System.out.println("making connection");
		 Connection conn=DriverManager.getConnection(  
				 dbHostUrl,dbUserName, dbPassword); 
		 return conn;
		 }catch(Exception e)
		 {
			 System.out.println("couldn't establish a JDBC connection");
			 e.printStackTrace();
			 return null;
		 }
		 
		 
	 }
	 
	 private List<Map<String, Object>> fetchDbRecords(String simpleSql) throws IllegalAccessException, InvocationTargetException, InstantiationException {
		 Map<String, Object> aRowColumnValue = new HashMap<>();
		 try {
			 System.out.println("inside fetch db");
			 Class.forName("com.mysql.jdbc.Driver");  
			 System.out.println("making connection");
			 Connection conn=DriverManager.getConnection(  
					 dbHostUrl,dbUserName, dbPassword); 
		 Statement stmt=conn.createStatement();  
		 ResultSet rs=stmt.executeQuery(simpleSql); 
		 ResultSetMetaData metaData = rs.getMetaData();
		// System.out.print("query result is"+metaData.toString());
		 int columnCount = metaData.getColumnCount();
		 while(rs.next()) {
			 String colName = metaData.getColumnName(1);
			 System.out.println("colname: "+colName);
			 String x = rs.getString(colName);
			 System.out.println("val: "+x);
			 break;
		//	 String columnValue =rs.getString(colName);
			// aRowColumnValue.put(colName, x);
		//	 aRowColumnValue.put(colName, columnValue);
		//	 break;
		 }
		 
//		 for (int j = 1; j <= columnCount; j++) {
//           String columnName = metaData.getColumnName(j);
//           Object columnValue = rs.getObject(columnName);
//
//           aRowColumnValue.put(columnName,+ columnValue);
//       }
		 }catch(Exception e)
		 {
			 e.printStackTrace();
		 }
		 
		 return (List<Map<String, Object>>) aRowColumnValue;
		 
	 }
	 
	 
	// }

}

//import org.springframework.jdbc.core.JdbcTemplate;
//import org.springframework.jdbc.datasource.SimpleDriverDataSource;
//import org.springframework.util.ClassUtils;
//import com.mysql.*;
//import com.mysql.jdbc.Driver;

//
//public class PostGresSqlExecutor {
//  private static final Logger LOGGER = LoggerFactory.getLogger(PostGresSqlExecutor.class);
//  Map<String, List<Map<String, Object>>> dbRecordsMap = new HashMap<>();
//  public static final String RESULTS_KEY = "rows";
//  Connection conn = null;
//
//  @Inject
//  @Named("db_host_url")
//  private String dbHostUrl;
//
//  @Inject
//  @Named("db_username")
//  private String dbUserName;
//
//  @Inject
//  @Named("db_password")
//  private String dbPassword;
//
//
//  public Map<String, List<Map<String, Object>>> executeSimpleSql(String simpleSql) throws IllegalAccessException, InvocationTargetException, InstantiationException {
//
//      LOGGER.info("DB - Executing SQL query: {}", simpleSql);
//
//      List<Map<String, Object>> recordsList = fetchDbRecords(simpleSql);
//
//      // -------------------------------------------------------
//      // Put all the fetched rows into nice JSON key and return.
//      // -- This make it better to assert SIZE etc in the steps.
//      // -- You can choose any key.
//      // -------------------------------------------------------
//      dbRecordsMap.put(RESULTS_KEY, recordsList);
//
//      return dbRecordsMap;
//  }
//
//  private List<Map<String, Object>> fetchDbRecords(String simpleSql) throws IllegalAccessException, InvocationTargetException, InstantiationException {
//      return getJdbcTemplate().query(simpleSql, (resultSet, i) -> {
//          Map<String, Object> aRowColumnValue = new HashMap<>();
//
//          ResultSetMetaData metaData = resultSet.getMetaData();
//          int columnCount = metaData.getColumnCount();
//
//          for (int j = 1; j <= columnCount; j++) {
//              String columnName = metaData.getColumnName(j);
//              Object columnValue = resultSet.getObject(columnName);
//
//              aRowColumnValue.put(columnName, columnValue);
//          }
//
//          return aRowColumnValue;
//      });
//  }
//
//  private JdbcTemplate getJdbcTemplate() throws IllegalAccessException, InvocationTargetException, InstantiationException {
//      final String driverClassName ="com.mysql.jdbc.Driver";
//      	//	"org.postgresql.Driver";
//      	//	"com.mysql.jdbc.Driver"; 
//  //    Class.forName("com.mysql.jdbc.Driver");
////      try {
////			Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
////		} catch (ClassNotFoundException e1) {
////			// TODO Auto-generated catch block
////			e1.printStackTrace();
////		}
//      		//"org.postgresql.Driver";
//
//      // Build dataSource & JDBC template from the host properties file
//      final Class<?> driverClass = ClassUtils.resolveClassName(driverClassName, this.getClass().getClassLoader());
//     // org.postgresql.Driver 
//  //    com.mysql.jdbc.Driver driver 
//      Driver driver = (Driver) ClassUtils.getConstructorIfAvailable(driverClass).newInstance();
// 
////      try {
////			conn =DriverManager.getConnection(dbHostUrl, dbUserName, dbPassword);
////			System.out.println("making connection");
////		} catch (SQLException e) {
////			// TODO Auto-generated catch block
////			e.printStackTrace();
////		}
//  //    final DataSource datasource=(DataSource) conn;
//      
//      final DataSource dataSource = new SimpleDriverDataSource(driver, dbHostUrl, dbUserName, dbPassword);
//
//      return new JdbcTemplate(dataSource);
//  }
//}

**Comment by authorjapps** [comment]
@AlindGit , can you push it to github and then, I can have a look ?
I think there might be an example/sample which works, please  have a look in the documentations/wiki.
